language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'
  - '4'

script:
  - npm test

#addons:
#  code_climate:
#    repo_token: 97196f6821cacf5c46ee5e1d187bdc8cec7cf3b2e3182d1a1a05c2aad00ec131

jobs:
  include:
#  - stage: coverage
#    node_js: 'node' # always use latest, take advantage of it being an extra test stage
#    script:
#      - npm run coverage
#    after_script:
#      - codeclimate-test-reporter < coverage/lcov.info
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Deploying to npm ..."
    after_script: skip
    deploy:
      provider: npm
      email: vatev.1+npm@gmail.com
      api_key:
        secure: vgFzvtXIScl3z1u5wBkze6DoaDpLz4g3NqMZuzWNJAw/n/kV+G82r3A7BvbW6653ldUGbePw7lg84g1t8iUM2jcIS0vYfrTlM2FKULZ+Vw1C7eLSEkJlbv4TCeAVpnBfPxY1FIt6/58gwaxfwVjit61SS56cu87iNP6ZFLWZqf57i1PatJWj7EZSYsHyY/3CwiNzqYXHdoCSmSHWmxor4aqH5FiIkJkNBtJC2ZKvRJigGAd483LLQ1/Lztgf0mqLQ3R8feWskOCbdbHiPU9KnJBNJ5Up9gqTybkxFEg9nNi04IN+xrGbXjd4SPSpdxbYFqg/Tob8YC0glcuwy6mlrKTSEX2Azl6f+ElyyJ+LxieoMZQxXbhB33/euGbAp06zrxId1xLW1V2N38vU0DXW2zWiDMB34dGvc9l5Gip5v1SG4UmO1DL0MOx/1p/ZoiNWz7lKSbDkIzQDIvNalAWEQYNZWO9ycjgMbD1fLspODXVU+1OGsUZQ4uFht9b34gxScIQVr2WSo42rk7gxxjdj8TJq10kc0154lGrzopjUM/7UY4Oeuus0NwYLTFD1AuBi3WPhRjaVo1vVJVj4l5uTTG7W34dTkTewyKC3y7OjB1BGvs8cYHzaOuvkxLnHm7Mv9bA2H/l+dpGXPjfQt4I0EHzkALb8mBHDSvcfNScGBC4=
      on:
        tags: true
        repo: catdad/runtime-required
